sudo: required
services:
  - docker

before_install:
  # Prepare test build
  - docker build -t degarza/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests
  - docker run -e CI=true degarza/react-test npm test

after_success:
  # Prepare prod builds
  - docker build -t denebgarza/multi-client ./client
  - docker build -t denebgarza/multi-nginx ./nginx
  - docker build -t denebgarza/multi-server ./server
  - docker build -t denebgarza/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push denebgarza/multi-client
  - docker push denebgarza/multi-nginx
  - docker push denebgarza/multi-server
  - docker push denebgarza/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-2
  env: Multidocker2-env
  bucket_name: elasticbeanstalk-us-east-1-554288963874
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY